language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-28
    - extra-android-m2repository

before_install:
  - cd $HOME
  - wget -q https://dl.google.com/android/repository/android-ndk-r17-linux-x86_64.zip
  - unzip -qq android-ndk-r17-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r17
  - cd $TRAVIS_BUILD_DIR
script:
  - ./gradlew assemble
