language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository

before_install:
  - cd $HOME
  - wget -q https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
  - unzip -qq android-ndk-r21-linux-x86_64.zip
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r21
  - cd $TRAVIS_BUILD_DIR
install:
  - echo y | sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'cmake;3.10.2.4988404'
  - echo y | sdkmanager 'lldb;3.1'
script:
  - ./gradlew assemble
